name = "QuantizedStateSystems"
uuid = "36fe21e9-7133-4048-96c4-5d0146746fd7"
authors = ["Zdeněk Hurák <hurak@fel.cvut.cz>"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
